
<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Macademy\Blog\ViewModel\Post $postVm */

$postVm = $block->getData('post_vm');
?>

<div class="blog-post-list">

    <p> <?= __('Blog Post list') ?> </p>
    <h1> <?= __('Blog posts') ?> </h1>
    <ul>

        <?php foreach ($postVm->getList() as $post): ?>
            <li>
                <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
                    <?= $post->getData('title') ?>
                    <?= $escaper->escapeHtml($post->getData('title')) ?>
                </a>
            </li>
        <?php endforeach ?>

    </ul>
<!--    Count  -->
    <p> <?= __('Post Count: %1' , $postVm->getCount()) ?> </p>   <!-- %1 => لازم اكتب دي عشان تظهر الرقم بتاعي الفعلي -->

</div>
