<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Macademy\Blog\ViewModel\Post $postVm */

$postVm = $block->getData('post_vm');
?>

<?php foreach ($postVm->getList() as $post): ?>

    <li>
        <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
            <?= $post->getData('title') ?>
            <?= $escaper->escapeHtml($post->getData('title')) ?>
        </a>
    </li>
<?php endforeach ?>
